: STAR 42 EMIT ;
: STARS 0 DO STAR LOOP ; 
: DOSTARS DUP 0 = INVERT IF 0 DO I 1 + DUP 2PAD ." / " I' . ." :" STARS CR LOOP .ELSE ." MUST BE GT 0" .THEN ;
: 2PAD DUP 10 < IF 48 EMIT .THEN . ;
: SPACE 32 EMIT ;
: TOP 0 DO STAR LOOP CR ; 
: BOTTOM TOP ;
: MIDDLE STAR 2 - 0 DO SPACE LOOP STAR CR ;
: BOX CR OVER TOP 2 - 0 DO DUP MIDDLE LOOP BOTTOM ;


