ELSE_S: .byte   ".ELSE",0
THEN_S: .byte   ".THEN",0    
TITLE:
    .byte "TFORTH 0.5 - AUG 2020",CR,LF,0
STACK_UFLOW_S:
    .byte "STACK UNDERFLOW",CR,LF,0
STACK_OFLOW_S:
    .byte "STACK OVERFLOW",CR,LF,0
NOT_IN_FUNCS:
    .byte "NOT IN FUNCTION",CR,LF,0
DEF_ERRS:
    .byte "DEFINITION ERROR",CR,LF,0
LOOP_ERRS:
    .byte "NOT IN LOOP",CR,LF,0
IF_ERRS:
    .byte "NOT IN IF BLOCK",CR,LF,0
THEN_ERRS:
    .byte ".THEN STATEMENT NOT FOUND",CR,LF,0
DIVZ_ERRS:
    .byte   "DIV BY ZERO",CR,LF,0
WHILE_ERRS:
    .byte   "NOT IN WHILE LOOP",CR,LF,0
LOOP_ENDS:
    .byte   "UNTERMINATED LOOP",CR,LF,0

